package com.chloe.weibo.core.dao;

import com.chloe.weibo.core.entity.RecomUser;
import com.chloe.weibo.core.entity.RecomUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecomUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int countByExample(RecomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int deleteByExample(RecomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int deleteByPrimaryKey(Integer recomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int insert(RecomUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int insertSelective(RecomUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    List<RecomUser> selectByExample(RecomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    RecomUser selectByPrimaryKey(Integer recomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") RecomUser record, @Param("example") RecomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int updateByExample(@Param("record") RecomUser record, @Param("example") RecomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int updateByPrimaryKeySelective(RecomUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recom_user
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    int updateByPrimaryKey(RecomUser record);
}