package com.chloe.weibo.core.dao;

import com.chloe.weibo.core.entity.UserData;
import com.chloe.weibo.core.entity.entityExample.UserDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int countByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int deleteByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int insert(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int insertSelective(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    List<UserData> selectByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    UserData selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserData record, @Param("example") UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int updateByExample(@Param("record") UserData record, @Param("example") UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int updateByPrimaryKeySelective(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    int updateByPrimaryKey(UserData record);
}