package com.chloe.weibo.core.entity;

import java.util.Date;

public class Comment {

    private Integer comId;
    private Integer userId;
    private Integer weiboId;
    private String comContent;
    private Date gmtCreate;
    private Date gmtModify;
    private Boolean isDel;

    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.com_id
     *
     * @param comId the value for tb_comment.com_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.user_id
     *
     * @return the value of tb_comment.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.user_id
     *
     * @param userId the value for tb_comment.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.weibo_id
     *
     * @return the value of tb_comment.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.weibo_id
     *
     * @param weiboId the value for tb_comment.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.com_content
     *
     * @return the value of tb_comment.com_content
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public String getComContent() {
        return comContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.com_content
     *
     * @param comContent the value for tb_comment.com_content
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setComContent(String comContent) {
        this.comContent = comContent == null ? null : comContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.gmt_create
     *
     * @return the value of tb_comment.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.gmt_create
     *
     * @param gmtCreate the value for tb_comment.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.gmt_modify
     *
     * @return the value of tb_comment.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.gmt_modify
     *
     * @param gmtModify the value for tb_comment.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_comment.is_del
     *
     * @return the value of tb_comment.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_comment.is_del
     *
     * @param isDel the value for tb_comment.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}