package com.chloe.weibo.core.entity;

public class Discuss {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discuss.discuss_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer discussId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discuss.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discuss.topic_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_discuss.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discuss.discuss_id
     *
     * @return the value of tb_discuss.discuss_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getDiscussId() {
        return discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discuss.discuss_id
     *
     * @param discussId the value for tb_discuss.discuss_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setDiscussId(Integer discussId) {
        this.discussId = discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discuss.weibo_id
     *
     * @return the value of tb_discuss.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discuss.weibo_id
     *
     * @param weiboId the value for tb_discuss.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discuss.topic_id
     *
     * @return the value of tb_discuss.topic_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discuss.topic_id
     *
     * @param topicId the value for tb_discuss.topic_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_discuss.is_del
     *
     * @return the value of tb_discuss.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_discuss.is_del
     *
     * @param isDel the value for tb_discuss.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}