package com.chloe.weibo.core.entity;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.file_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.file_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.file_address
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private String fileAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_file.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.file_id
     *
     * @return the value of tb_file.file_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.file_id
     *
     * @param fileId the value for tb_file.file_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.weibo_id
     *
     * @return the value of tb_file.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.weibo_id
     *
     * @param weiboId the value for tb_file.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.file_type
     *
     * @return the value of tb_file.file_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.file_type
     *
     * @param fileType the value for tb_file.file_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.file_address
     *
     * @return the value of tb_file.file_address
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public String getFileAddress() {
        return fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.file_address
     *
     * @param fileAddress the value for tb_file.file_address
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress == null ? null : fileAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_file.is_del
     *
     * @return the value of tb_file.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_file.is_del
     *
     * @param isDel the value for tb_file.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}