package com.chloe.weibo.core.entity;

public class Forwarding {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_forwarding.forwarding_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer forwardingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_forwarding.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_forwarding.org_weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer orgWeiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_forwarding.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_forwarding.forwarding_id
     *
     * @return the value of tb_forwarding.forwarding_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getForwardingId() {
        return forwardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_forwarding.forwarding_id
     *
     * @param forwardingId the value for tb_forwarding.forwarding_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setForwardingId(Integer forwardingId) {
        this.forwardingId = forwardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_forwarding.weibo_id
     *
     * @return the value of tb_forwarding.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_forwarding.weibo_id
     *
     * @param weiboId the value for tb_forwarding.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_forwarding.org_weibo_id
     *
     * @return the value of tb_forwarding.org_weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getOrgWeiboId() {
        return orgWeiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_forwarding.org_weibo_id
     *
     * @param orgWeiboId the value for tb_forwarding.org_weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setOrgWeiboId(Integer orgWeiboId) {
        this.orgWeiboId = orgWeiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_forwarding.is_del
     *
     * @return the value of tb_forwarding.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_forwarding.is_del
     *
     * @param isDel the value for tb_forwarding.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}