package com.chloe.weibo.core.entity;

import java.util.Date;

public class Like {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.collection_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer weiboId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.collection_id
     *
     * @return the value of tb_collection.collection_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.collection_id
     *
     * @param collectionId the value for tb_collection.collection_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setCollectionId(Integer collectionId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.user_id
     *
     * @return the value of tb_collection.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.user_id
     *
     * @param userId the value for tb_collection.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.weibo_id
     *
     * @return the value of tb_collection.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.weibo_id
     *
     * @param weiboId the value for tb_collection.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.gmt_create
     *
     * @return the value of tb_collection.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.gmt_create
     *
     * @param gmtCreate the value for tb_collection.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.gmt_modify
     *
     * @return the value of tb_collection.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.gmt_modify
     *
     * @param gmtModify the value for tb_collection.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.is_del
     *
     * @return the value of tb_collection.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.is_del
     *
     * @param isDel the value for tb_collection.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}