package com.chloe.weibo.core.entity;

import java.util.Objects;

public class RecomUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.user_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user1_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user2_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user3_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser3Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user4_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser4Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user5_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser5Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user6_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser6Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user7_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser7Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user8_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser8Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user9_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser9Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recom_user.recom_user10_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    private Integer recomUser10Id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_id
     *
     * @return the value of tb_recom_user.recom_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomId() {
        return recomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_id
     *
     * @param recomId the value for tb_recom_user.recom_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomId(Integer recomId) {
        this.recomId = recomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.user_id
     *
     * @return the value of tb_recom_user.user_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.user_id
     *
     * @param userId the value for tb_recom_user.user_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user1_id
     *
     * @return the value of tb_recom_user.recom_user1_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser1Id() {
        return recomUser1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user1_id
     *
     * @param recomUser1Id the value for tb_recom_user.recom_user1_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser1Id(Integer recomUser1Id) {
        this.recomUser1Id = recomUser1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user2_id
     *
     * @return the value of tb_recom_user.recom_user2_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser2Id() {
        return recomUser2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user2_id
     *
     * @param recomUser2Id the value for tb_recom_user.recom_user2_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser2Id(Integer recomUser2Id) {
        this.recomUser2Id = recomUser2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user3_id
     *
     * @return the value of tb_recom_user.recom_user3_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser3Id() {
        return recomUser3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user3_id
     *
     * @param recomUser3Id the value for tb_recom_user.recom_user3_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser3Id(Integer recomUser3Id) {
        this.recomUser3Id = recomUser3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user4_id
     *
     * @return the value of tb_recom_user.recom_user4_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser4Id() {
        return recomUser4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user4_id
     *
     * @param recomUser4Id the value for tb_recom_user.recom_user4_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser4Id(Integer recomUser4Id) {
        this.recomUser4Id = recomUser4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user5_id
     *
     * @return the value of tb_recom_user.recom_user5_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser5Id() {
        return recomUser5Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user5_id
     *
     * @param recomUser5Id the value for tb_recom_user.recom_user5_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser5Id(Integer recomUser5Id) {
        this.recomUser5Id = recomUser5Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user6_id
     *
     * @return the value of tb_recom_user.recom_user6_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser6Id() {
        return recomUser6Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user6_id
     *
     * @param recomUser6Id the value for tb_recom_user.recom_user6_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser6Id(Integer recomUser6Id) {
        this.recomUser6Id = recomUser6Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user7_id
     *
     * @return the value of tb_recom_user.recom_user7_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser7Id() {
        return recomUser7Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user7_id
     *
     * @param recomUser7Id the value for tb_recom_user.recom_user7_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser7Id(Integer recomUser7Id) {
        this.recomUser7Id = recomUser7Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user8_id
     *
     * @return the value of tb_recom_user.recom_user8_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser8Id() {
        return recomUser8Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user8_id
     *
     * @param recomUser8Id the value for tb_recom_user.recom_user8_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser8Id(Integer recomUser8Id) {
        this.recomUser8Id = recomUser8Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user9_id
     *
     * @return the value of tb_recom_user.recom_user9_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser9Id() {
        return recomUser9Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user9_id
     *
     * @param recomUser9Id the value for tb_recom_user.recom_user9_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser9Id(Integer recomUser9Id) {
        this.recomUser9Id = recomUser9Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recom_user.recom_user10_id
     *
     * @return the value of tb_recom_user.recom_user10_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public Integer getRecomUser10Id() {
        return recomUser10Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recom_user.recom_user10_id
     *
     * @param recomUser10Id the value for tb_recom_user.recom_user10_id
     *
     * @mbggenerated Sat May 25 20:24:43 CST 2019
     */
    public void setRecomUser10Id(Integer recomUser10Id) {
        this.recomUser10Id = recomUser10Id;
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        RecomUser recomUser = (RecomUser) object;
        return Objects.equals(recomId, recomUser.recomId) &&
                Objects.equals(userId, recomUser.userId) &&
                Objects.equals(recomUser1Id, recomUser.recomUser1Id) &&
                Objects.equals(recomUser2Id, recomUser.recomUser2Id) &&
                Objects.equals(recomUser3Id, recomUser.recomUser3Id) &&
                Objects.equals(recomUser4Id, recomUser.recomUser4Id) &&
                Objects.equals(recomUser5Id, recomUser.recomUser5Id) &&
                Objects.equals(recomUser6Id, recomUser.recomUser6Id) &&
                Objects.equals(recomUser7Id, recomUser.recomUser7Id) &&
                Objects.equals(recomUser8Id, recomUser.recomUser8Id) &&
                Objects.equals(recomUser9Id, recomUser.recomUser9Id) &&
                Objects.equals(recomUser10Id, recomUser.recomUser10Id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recomId, userId, recomUser1Id, recomUser2Id, recomUser3Id, recomUser4Id, recomUser5Id, recomUser6Id, recomUser7Id, recomUser8Id, recomUser9Id, recomUser10Id);
    }
}