package com.chloe.weibo.core.entity;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tag.tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tag.tag_name
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tag.use_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer useAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_tag.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag.tag_id
     *
     * @return the value of tb_tag.tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag.tag_id
     *
     * @param tagId the value for tb_tag.tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag.tag_name
     *
     * @return the value of tb_tag.tag_name
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag.tag_name
     *
     * @param tagName the value for tb_tag.tag_name
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag.use_amount
     *
     * @return the value of tb_tag.use_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getUseAmount() {
        return useAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag.use_amount
     *
     * @param useAmount the value for tb_tag.use_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setUseAmount(Integer useAmount) {
        this.useAmount = useAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag.is_del
     *
     * @return the value of tb_tag.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag.is_del
     *
     * @param isDel the value for tb_tag.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}