package com.chloe.weibo.core.entity;

import java.util.Date;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topic.topic_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topic.topic_name
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private String topicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topic.discuss_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer discussAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topic.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topic.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_topic.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topic.topic_id
     *
     * @return the value of tb_topic.topic_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topic.topic_id
     *
     * @param topicId the value for tb_topic.topic_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topic.topic_name
     *
     * @return the value of tb_topic.topic_name
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topic.topic_name
     *
     * @param topicName the value for tb_topic.topic_name
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topic.discuss_amount
     *
     * @return the value of tb_topic.discuss_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getDiscussAmount() {
        return discussAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topic.discuss_amount
     *
     * @param discussAmount the value for tb_topic.discuss_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setDiscussAmount(Integer discussAmount) {
        this.discussAmount = discussAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topic.gmt_create
     *
     * @return the value of tb_topic.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topic.gmt_create
     *
     * @param gmtCreate the value for tb_topic.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topic.gmt_modify
     *
     * @return the value of tb_topic.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topic.gmt_modify
     *
     * @param gmtModify the value for tb_topic.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_topic.is_del
     *
     * @return the value of tb_topic.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_topic.is_del
     *
     * @param isDel the value for tb_topic.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}