package com.chloe.weibo.core.entity;

import com.chloe.weibo.pojo.vo.UserVo;

import java.util.Date;
import java.util.Objects;

public class User {
    private Integer userId;
    private String logName;
    private String userPassword;
    private String nickName;
    private String emailAddress;
    private String phoneNumber;
    private String userAvatar;
    private String userGender;
    private String userPerSignature;
    private String userPlace;
    private String city;
    private Date userBirthday;
    private Date gmtCreate;
    private Date gmtModify;
    private Boolean isTag;
    private Boolean isDel;
    private Boolean isVip;
    private Boolean isIdentify;
    private String authentication;
    private Integer vipLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.log_name
     *
     * @return the value of tb_user.log_name
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getLogName() {
        return logName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.log_name
     *
     * @param logName the value for tb_user.log_name
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setLogName(String logName) {
        this.logName = logName == null ? null : logName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_password
     *
     * @return the value of tb_user.user_password
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_password
     *
     * @param userPassword the value for tb_user.user_password
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.nick_name
     *
     * @return the value of tb_user.nick_name
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.nick_name
     *
     * @param nickName the value for tb_user.nick_name
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email_address
     *
     * @return the value of tb_user.email_address
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email_address
     *
     * @param emailAddress the value for tb_user.email_address
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone_number
     *
     * @return the value of tb_user.phone_number
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone_number
     *
     * @param phoneNumber the value for tb_user.phone_number
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_avatar
     *
     * @return the value of tb_user.user_avatar
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_avatar
     *
     * @param userAvatar the value for tb_user.user_avatar
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_gender
     *
     * @return the value of tb_user.user_gender
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_gender
     *
     * @param userGender the value for tb_user.user_gender
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_per_signature
     *
     * @return the value of tb_user.user_per_signature
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getUserPerSignature() {
        return userPerSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_per_signature
     *
     * @param userPerSignature the value for tb_user.user_per_signature
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserPerSignature(String userPerSignature) {
        this.userPerSignature = userPerSignature == null ? null : userPerSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_place
     *
     * @return the value of tb_user.user_place
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getUserPlace() {
        return userPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_place
     *
     * @param userPlace the value for tb_user.user_place
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserPlace(String userPlace) {
        this.userPlace = userPlace == null ? null : userPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.city
     *
     * @return the value of tb_user.city
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.city
     *
     * @param city the value for tb_user.city
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_birthday
     *
     * @return the value of tb_user.user_birthday
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_birthday
     *
     * @param userBirthday the value for tb_user.user_birthday
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.gmt_create
     *
     * @return the value of tb_user.gmt_create
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.gmt_create
     *
     * @param gmtCreate the value for tb_user.gmt_create
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.gmt_modify
     *
     * @return the value of tb_user.gmt_modify
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.gmt_modify
     *
     * @param gmtModify the value for tb_user.gmt_modify
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.is_tag
     *
     * @return the value of tb_user.is_tag
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Boolean getIsTag() {
        return isTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.is_tag
     *
     * @param isTag the value for tb_user.is_tag
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setIsTag(Boolean isTag) {
        this.isTag = isTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.is_del
     *
     * @return the value of tb_user.is_del
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.is_del
     *
     * @param isDel the value for tb_user.is_del
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.is_vip
     *
     * @return the value of tb_user.is_vip
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Boolean getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.is_vip
     *
     * @param isVip the value for tb_user.is_vip
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setIsVip(Boolean isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.is_identify
     *
     * @return the value of tb_user.is_identify
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Boolean getIsIdentify() {
        return isIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.is_identify
     *
     * @param isIdentify the value for tb_user.is_identify
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setIsIdentify(Boolean isIdentify) {
        this.isIdentify = isIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.authentication
     *
     * @return the value of tb_user.authentication
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public String getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.authentication
     *
     * @param authentication the value for tb_user.authentication
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setAuthentication(String authentication) {
        this.authentication = authentication == null ? null : authentication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.vip_level
     *
     * @return the value of tb_user.vip_level
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public Integer getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.vip_level
     *
     * @param vipLevel the value for tb_user.vip_level
     *
     * @mbggenerated Mon May 06 17:06:20 CST 2019
     */
    public void setVipLevel(Integer vipLevel) {
        this.vipLevel = vipLevel;
    }
    public User() {
    }

    public User(UserVo userVo) {
        this.userId = userVo.getUserId();
        this.logName = userVo.getLogName();
        this.userPassword = userVo.getUserPassword();
        this.nickName = userVo.getNickName();
        this.emailAddress = userVo.getEmailAddress();
        this.phoneNumber = userVo.getPhoneNumber();
        this.userAvatar = userVo.getUserAvatar();
        this.userGender = userVo.getUserGender();
        this.userPerSignature = userVo.getUserPerSignature();
        this.userPlace = userVo.getUserPlace();
        this.userBirthday = userVo.getUserBirthday();
        this.gmtCreate=new Date();
        this.gmtModify=new Date();
        this.isTag = userVo.getTag();
        this.isDel = false;
        this.city=userVo.getCity();
        this.isVip=userVo.getVip();
        this.isIdentify=userVo.getIdentify();
        this.authentication=userVo.getAuthentication();
        this.vipLevel=userVo.getVipLevel();
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        User user = (User) object;
        return Objects.equals(userId, user.userId) &&
                Objects.equals(logName, user.logName) &&
                Objects.equals(userPassword, user.userPassword) &&
                Objects.equals(nickName, user.nickName) &&
                Objects.equals(emailAddress, user.emailAddress) &&
                Objects.equals(phoneNumber, user.phoneNumber) &&
                Objects.equals(userAvatar, user.userAvatar) &&
                Objects.equals(userGender, user.userGender) &&
                Objects.equals(userPerSignature, user.userPerSignature) &&
                Objects.equals(userPlace, user.userPlace) &&
                Objects.equals(userBirthday, user.userBirthday) &&
                Objects.equals(isTag, user.isTag) &&
                Objects.equals(isDel, user.isDel)&&
                Objects.equals(city,user.city)&&
                Objects.equals(isVip,user.isVip)&&
                Objects.equals(isIdentify,user.isIdentify)&&
                Objects.equals(authentication,user.authentication)&&
                Objects.equals(vipLevel,user.getVipLevel());
    }
}