package com.chloe.weibo.core.entity;

public class UserTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_tag.user_tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer userTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_tag.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_tag.tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_tag.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_tag.user_tag_id
     *
     * @return the value of tb_user_tag.user_tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getUserTagId() {
        return userTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_tag.user_tag_id
     *
     * @param userTagId the value for tb_user_tag.user_tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setUserTagId(Integer userTagId) {
        this.userTagId = userTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_tag.user_id
     *
     * @return the value of tb_user_tag.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_tag.user_id
     *
     * @param userId the value for tb_user_tag.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_tag.tag_id
     *
     * @return the value of tb_user_tag.tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_tag.tag_id
     *
     * @param tagId the value for tb_user_tag.tag_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_tag.is_del
     *
     * @return the value of tb_user_tag.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_tag.is_del
     *
     * @param isDel the value for tb_user_tag.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}