package com.chloe.weibo.core.entity;

import com.chloe.weibo.pojo.vo.WeiboVo;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

public class Weibo {

    private Integer weiboId;
    private Integer userId;
    private Integer publishType;
    private String weiboContent;
    private Boolean weiboType;
    private Integer forwardingAmount;
    private Integer commentAmount;
    private Integer likeAmount;
    private Date gmtCreate;
    private Date gmtModify;
    private Boolean isOnlyText;
    private Boolean isTopic;
    private Boolean isModify;
    private Boolean isDel;

    public Integer getWeiboId() {
        return weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.weibo_id
     *
     * @param weiboId the value for tb_weibo.weibo_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboId(Integer weiboId) {
        this.weiboId = weiboId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.user_id
     *
     * @return the value of tb_weibo.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.user_id
     *
     * @param userId the value for tb_weibo.user_id
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.publish_type
     *
     * @return the value of tb_weibo.publish_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getPublishType() {
        return publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.publish_type
     *
     * @param publishType the value for tb_weibo.publish_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setPublishType(Integer publishType) {
        this.publishType = publishType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.weibo_content
     *
     * @return the value of tb_weibo.weibo_content
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public String getWeiboContent() {
        return weiboContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.weibo_content
     *
     * @param weiboContent the value for tb_weibo.weibo_content
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboContent(String weiboContent) {
        this.weiboContent = weiboContent == null ? null : weiboContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.weibo_type
     *
     * @return the value of tb_weibo.weibo_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getWeiboType() {
        return weiboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.weibo_type
     *
     * @param weiboType the value for tb_weibo.weibo_type
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setWeiboType(Boolean weiboType) {
        this.weiboType = weiboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.forwarding_amount
     *
     * @return the value of tb_weibo.forwarding_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getForwardingAmount() {
        return forwardingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.forwarding_amount
     *
     * @param forwardingAmount the value for tb_weibo.forwarding_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setForwardingAmount(Integer forwardingAmount) {
        this.forwardingAmount = forwardingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.comment_amount
     *
     * @return the value of tb_weibo.comment_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getCommentAmount() {
        return commentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.comment_amount
     *
     * @param commentAmount the value for tb_weibo.comment_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setCommentAmount(Integer commentAmount) {
        this.commentAmount = commentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.like_amount
     *
     * @return the value of tb_weibo.like_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Integer getLikeAmount() {
        return likeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.like_amount
     *
     * @param likeAmount the value for tb_weibo.like_amount
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setLikeAmount(Integer likeAmount) {
        this.likeAmount = likeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.gmt_create
     *
     * @return the value of tb_weibo.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.gmt_create
     *
     * @param gmtCreate the value for tb_weibo.gmt_create
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.gmt_modify
     *
     * @return the value of tb_weibo.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.gmt_modify
     *
     * @param gmtModify the value for tb_weibo.gmt_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.is_only_text
     *
     * @return the value of tb_weibo.is_only_text
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsOnlyText() {
        return isOnlyText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.is_only_text
     *
     * @param isOnlyText the value for tb_weibo.is_only_text
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsOnlyText(Boolean isOnlyText) {
        this.isOnlyText = isOnlyText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.is_topic
     *
     * @return the value of tb_weibo.is_topic
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsTopic() {
        return isTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.is_topic
     *
     * @param isTopic the value for tb_weibo.is_topic
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsTopic(Boolean isTopic) {
        this.isTopic = isTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.is_modify
     *
     * @return the value of tb_weibo.is_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsModify() {
        return isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.is_modify
     *
     * @param isModify the value for tb_weibo.is_modify
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsModify(Boolean isModify) {
        this.isModify = isModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weibo.is_del
     *
     * @return the value of tb_weibo.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weibo.is_del
     *
     * @param isDel the value for tb_weibo.is_del
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    @Override
    public boolean equals(Object object) {
        if (this == object) return true;
        if (object == null || getClass() != object.getClass()) return false;
        Weibo weibo = (Weibo) object;
        return Objects.equals(weiboId, weibo.weiboId) &&
                Objects.equals(userId, weibo.userId) &&
                Objects.equals(publishType, weibo.publishType) &&
                Objects.equals(weiboContent, weibo.weiboContent) &&
                Objects.equals(weiboType, weibo.weiboType);
    }

    public Weibo(Integer userId, Integer publishType, String weiboContent, Boolean weiboType, Integer forwardingAmount, Integer commentAmount, Integer likeAmount, Date gmtCreate, Date gmtModify, Boolean isOnlyText, Boolean isTopic, Boolean isModify, Boolean isDel) {
        this.userId = userId;
        this.publishType = publishType;
        this.weiboContent = weiboContent;
        this.weiboType = weiboType;
        this.forwardingAmount = forwardingAmount;
        this.commentAmount = commentAmount;
        this.likeAmount = likeAmount;
        this.gmtCreate = gmtCreate;
        this.gmtModify = gmtModify;
        this.isOnlyText = isOnlyText;
        this.isTopic = isTopic;
        this.isModify = isModify;
        this.isDel = isDel;
    }

    public Weibo() {
    }

    public Weibo(WeiboVo weiboVo) throws ParseException {
        this.weiboId = weiboVo.getWeiboId();
        this.userId = weiboVo.getUserId();
        this.publishType = weiboVo.getPublishType();
        this.weiboContent = weiboVo.getWeiboContent();
        this.weiboType = weiboVo.getWeiboType();
        this.forwardingAmount = weiboVo.getForwardingAmount();
        this.commentAmount = weiboVo.getCommentAmount();
        this.likeAmount = weiboVo.getLikeAmount();
        if (weiboVo.getGmtCreate()!=""&&weiboVo.getGmtCreate()!=null){
            DateFormat dtf=DateFormat.getDateTimeInstance();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            this.gmtCreate = sdf.parse(weiboVo.getGmtCreate());
        }
        this.isOnlyText = weiboVo.getIsOnlyText();
        this.isTopic = weiboVo.getIsTopic();
        this.isModify = weiboVo.getIsModify();
    }
}