package com.chloe.weibo.core.entity.entityExample;

import java.util.ArrayList;
import java.util.List;

public class ForwardingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public ForwardingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andForwardingIdIsNull() {
            addCriterion("forwarding_id is null");
            return (Criteria) this;
        }

        public Criteria andForwardingIdIsNotNull() {
            addCriterion("forwarding_id is not null");
            return (Criteria) this;
        }

        public Criteria andForwardingIdEqualTo(Integer value) {
            addCriterion("forwarding_id =", value, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdNotEqualTo(Integer value) {
            addCriterion("forwarding_id <>", value, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdGreaterThan(Integer value) {
            addCriterion("forwarding_id >", value, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("forwarding_id >=", value, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdLessThan(Integer value) {
            addCriterion("forwarding_id <", value, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdLessThanOrEqualTo(Integer value) {
            addCriterion("forwarding_id <=", value, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdIn(List<Integer> values) {
            addCriterion("forwarding_id in", values, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdNotIn(List<Integer> values) {
            addCriterion("forwarding_id not in", values, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdBetween(Integer value1, Integer value2) {
            addCriterion("forwarding_id between", value1, value2, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andForwardingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("forwarding_id not between", value1, value2, "forwardingId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdIsNull() {
            addCriterion("weibo_id is null");
            return (Criteria) this;
        }

        public Criteria andWeiboIdIsNotNull() {
            addCriterion("weibo_id is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboIdEqualTo(Integer value) {
            addCriterion("weibo_id =", value, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdNotEqualTo(Integer value) {
            addCriterion("weibo_id <>", value, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdGreaterThan(Integer value) {
            addCriterion("weibo_id >", value, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("weibo_id >=", value, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdLessThan(Integer value) {
            addCriterion("weibo_id <", value, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdLessThanOrEqualTo(Integer value) {
            addCriterion("weibo_id <=", value, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdIn(List<Integer> values) {
            addCriterion("weibo_id in", values, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdNotIn(List<Integer> values) {
            addCriterion("weibo_id not in", values, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdBetween(Integer value1, Integer value2) {
            addCriterion("weibo_id between", value1, value2, "weiboId");
            return (Criteria) this;
        }

        public Criteria andWeiboIdNotBetween(Integer value1, Integer value2) {
            addCriterion("weibo_id not between", value1, value2, "weiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdIsNull() {
            addCriterion("org_weibo_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdIsNotNull() {
            addCriterion("org_weibo_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdEqualTo(Integer value) {
            addCriterion("org_weibo_id =", value, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdNotEqualTo(Integer value) {
            addCriterion("org_weibo_id <>", value, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdGreaterThan(Integer value) {
            addCriterion("org_weibo_id >", value, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("org_weibo_id >=", value, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdLessThan(Integer value) {
            addCriterion("org_weibo_id <", value, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdLessThanOrEqualTo(Integer value) {
            addCriterion("org_weibo_id <=", value, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdIn(List<Integer> values) {
            addCriterion("org_weibo_id in", values, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdNotIn(List<Integer> values) {
            addCriterion("org_weibo_id not in", values, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdBetween(Integer value1, Integer value2) {
            addCriterion("org_weibo_id between", value1, value2, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andOrgWeiboIdNotBetween(Integer value1, Integer value2) {
            addCriterion("org_weibo_id not between", value1, value2, "orgWeiboId");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_forwarding
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 08 15:40:48 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_forwarding
     *
     * @mbggenerated Mon Apr 08 15:40:48 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}