package com.chloe.weibo.core.entity.entityExample;

import java.util.ArrayList;
import java.util.List;

public class UserDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public UserDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountIsNull() {
            addCriterion("weibo_amount is null");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountIsNotNull() {
            addCriterion("weibo_amount is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountEqualTo(Integer value) {
            addCriterion("weibo_amount =", value, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountNotEqualTo(Integer value) {
            addCriterion("weibo_amount <>", value, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountGreaterThan(Integer value) {
            addCriterion("weibo_amount >", value, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("weibo_amount >=", value, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountLessThan(Integer value) {
            addCriterion("weibo_amount <", value, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountLessThanOrEqualTo(Integer value) {
            addCriterion("weibo_amount <=", value, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountIn(List<Integer> values) {
            addCriterion("weibo_amount in", values, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountNotIn(List<Integer> values) {
            addCriterion("weibo_amount not in", values, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountBetween(Integer value1, Integer value2) {
            addCriterion("weibo_amount between", value1, value2, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andWeiboAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("weibo_amount not between", value1, value2, "weiboAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountIsNull() {
            addCriterion("be_followed_amount is null");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountIsNotNull() {
            addCriterion("be_followed_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountEqualTo(Integer value) {
            addCriterion("be_followed_amount =", value, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountNotEqualTo(Integer value) {
            addCriterion("be_followed_amount <>", value, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountGreaterThan(Integer value) {
            addCriterion("be_followed_amount >", value, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("be_followed_amount >=", value, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountLessThan(Integer value) {
            addCriterion("be_followed_amount <", value, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountLessThanOrEqualTo(Integer value) {
            addCriterion("be_followed_amount <=", value, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountIn(List<Integer> values) {
            addCriterion("be_followed_amount in", values, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountNotIn(List<Integer> values) {
            addCriterion("be_followed_amount not in", values, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountBetween(Integer value1, Integer value2) {
            addCriterion("be_followed_amount between", value1, value2, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andBeFollowedAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("be_followed_amount not between", value1, value2, "beFollowedAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountIsNull() {
            addCriterion("follow_amount is null");
            return (Criteria) this;
        }

        public Criteria andFollowAmountIsNotNull() {
            addCriterion("follow_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFollowAmountEqualTo(Integer value) {
            addCriterion("follow_amount =", value, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountNotEqualTo(Integer value) {
            addCriterion("follow_amount <>", value, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountGreaterThan(Integer value) {
            addCriterion("follow_amount >", value, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("follow_amount >=", value, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountLessThan(Integer value) {
            addCriterion("follow_amount <", value, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountLessThanOrEqualTo(Integer value) {
            addCriterion("follow_amount <=", value, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountIn(List<Integer> values) {
            addCriterion("follow_amount in", values, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountNotIn(List<Integer> values) {
            addCriterion("follow_amount not in", values, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountBetween(Integer value1, Integer value2) {
            addCriterion("follow_amount between", value1, value2, "followAmount");
            return (Criteria) this;
        }

        public Criteria andFollowAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("follow_amount not between", value1, value2, "followAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountIsNull() {
            addCriterion("mutual_amount is null");
            return (Criteria) this;
        }

        public Criteria andMutualAmountIsNotNull() {
            addCriterion("mutual_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMutualAmountEqualTo(Integer value) {
            addCriterion("mutual_amount =", value, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountNotEqualTo(Integer value) {
            addCriterion("mutual_amount <>", value, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountGreaterThan(Integer value) {
            addCriterion("mutual_amount >", value, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("mutual_amount >=", value, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountLessThan(Integer value) {
            addCriterion("mutual_amount <", value, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountLessThanOrEqualTo(Integer value) {
            addCriterion("mutual_amount <=", value, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountIn(List<Integer> values) {
            addCriterion("mutual_amount in", values, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountNotIn(List<Integer> values) {
            addCriterion("mutual_amount not in", values, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountBetween(Integer value1, Integer value2) {
            addCriterion("mutual_amount between", value1, value2, "mutualAmount");
            return (Criteria) this;
        }

        public Criteria andMutualAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("mutual_amount not between", value1, value2, "mutualAmount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_userdata
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 13 19:53:05 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_userdata
     *
     * @mbggenerated Sat Apr 13 19:53:05 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}